# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('preview', models.TextField(max_length=500)),
                ('picture', models.TextField(max_length=500)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.PlayList')),
            ],
        ),
    ]
