# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='picture',
            new_name='album_picture',
        ),
        migrations.AddField(
            model_name='music',
            name='artist_picture',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
