# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='id_num',
            new_name='album_id',
        ),
        migrations.AddField(
            model_name='music',
            name='album_title',
            field=models.CharField(default='album_title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='song_id',
            field=models.CharField(default='song_id', max_length=255),
            preserve_default=False,
        ),
    ]
