# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170410_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='password2',
        ),
    ]
