# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170331_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password1',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='password2',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
