# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170404_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
