# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20170420_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='like_user_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
